[build]
builder = "NIXPACKS"
buildCommand = "npm run build"

[deploy]
# Use the Node SPA server to support client-side routing
startCommand = "node server.js"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[env]
NODE_ENV = "production"
