apiVersion: 1

policies:
  - orgId: 1
    receiver: default-receiver
    group_by: ['alertname', 'cluster', 'service']
    group_wait: 10s
    group_interval: 5m
    repeat_interval: 12h
    routes:
      - receiver: midnight-critical
        matchers:
          - severity = critical
          - process = midnight_reset
        group_wait: 0s
        group_interval: 1m
        repeat_interval: 30m
        
      - receiver: devops-team
        matchers:
          - team = devops
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 4h

reset_policies: []

templates: []
