apiVersion: 1

groups:
  - name: midnight_reset_alerts
    orgId: 1
    folder: alerts
    interval: 1m
    rules:
      - uid: midnight_errors_001
        title: "Midnight Reset Errors"
        condition: C
        data:
          - refId: A
            queryType: ""
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: loki
            model:
              expr: |
                count_over_time({container=~"escashop-backend.*"} 
                |~ "(?i)(error|failed|exception)" 
                |~ "(?i)(reset|midnight|scheduler|00:00|23:59)" [5m])
              intervalMs: 1000
              maxDataPoints: 43200
          - refId: B
            queryType: ""
            relativeTimeRange:
              from: 0
              to: 0
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params: []
                    type: gt
                  operator:
                    type: and
                  query:
                    params:
                      - B
                  reducer:
                    params: []
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: A
              intervalMs: 1000
              maxDataPoints: 43200
              reducer: last
              type: reduce
          - refId: C
            queryType: ""
            relativeTimeRange:
              from: 0
              to: 0
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params:
                      - 0
                      - 0
                    type: gt
                  operator:
                    type: and
                  query:
                    params:
                      - C
                  reducer:
                    params: []
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: B
              intervalMs: 1000
              maxDataPoints: 43200
              reducer: last
              type: threshold
        noDataState: NoData
        execErrState: Alerting
        for: 30s
        annotations:
          description: "Midnight reset errors detected in escashop application logs. Check logs for specific error details."
          runbook_url: "https://docs.escashop.com/runbooks/midnight-reset-troubleshooting"
          summary: "{{ $labels.container }} has reported errors during midnight reset process"
        labels:
          severity: critical
          team: devops
          component: scheduler
          process: midnight_reset

      - uid: midnight_reset_failure_002
        title: "Midnight Reset Process Failure"
        condition: C
        data:
          - refId: A
            queryType: ""
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: loki
            model:
              expr: |
                count_over_time({container=~"escashop-backend.*"} 
                |~ "reset completed successfully" [5m])
              intervalMs: 1000
              maxDataPoints: 43200
          - refId: B
            queryType: ""
            relativeTimeRange:
              from: 0
              to: 0
            datasourceUid: __expr__
            model:
              expression: A
              reducer: last
              type: reduce
          - refId: C
            queryType: ""
            relativeTimeRange:
              from: 0
              to: 0
            datasourceUid: __expr__
            model:
              expression: B
              reducer: last
              type: threshold
              conditions:
                - evaluator:
                    params: [0]
                    type: lt
        noDataState: Alerting
        execErrState: Alerting
        for: 5m
        annotations:
          description: "Midnight reset process has not completed successfully within expected timeframe. Manual intervention may be required."
          runbook_url: "https://docs.escashop.com/runbooks/midnight-reset-recovery"
          summary: "Midnight reset process appears to have failed - no success message detected"
        labels:
          severity: critical
          team: devops
          component: scheduler
          process: midnight_reset

      - uid: midnight_queue_anomaly_003
        title: "Midnight Queue Reset Anomaly"
        condition: C
        data:
          - refId: A
            queryType: ""
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: loki
            model:
              expr: |
                count_over_time({container=~"escashop-backend.*"} 
                |~ "(?i)(queue.*error|queue.*failed|queue.*exception)" 
                | __time__ >= "23:50" and __time__ <= "00:10" [10m])
              intervalMs: 1000
              maxDataPoints: 43200
          - refId: B
            queryType: ""
            relativeTimeRange:
              from: 0
              to: 0
            datasourceUid: __expr__
            model:
              expression: A
              reducer: last
              type: reduce
          - refId: C
            queryType: ""
            relativeTimeRange:
              from: 0
              to: 0
            datasourceUid: __expr__
            model:
              expression: B
              reducer: last
              type: threshold
              conditions:
                - evaluator:
                    params: [2]
                    type: gt
        noDataState: NoData
        execErrState: Alerting
        for: 1m
        annotations:
          description: "Queue-related errors detected during midnight reset window (23:50-00:10 PH time)"
          runbook_url: "https://docs.escashop.com/runbooks/queue-troubleshooting"
          summary: "Queue system errors during midnight reset period"
        labels:
          severity: warning
          team: devops
          component: queue
          process: midnight_reset
